// Emits results/latex/generated_policy_macros.tex from the deployed-engine (Cedar) cross-check.
// No number is hand-typed: the paper's deployed-engine claims read from results/eval/cedar-policy-comparator.json.
import { readFileSync, writeFileSync } from "node:fs";

const c = JSON.parse(readFileSync("results/eval/cedar-policy-comparator.json", "utf8"));

const lines = [
  "% Auto-generated by scripts/export_policy_engine_macros.mjs -- deployed-engine (Cedar) cross-check.",
  `\\newcommand{\\cedarVersion}{${c.engine_version}}`,
  `\\newcommand{\\cedarTotal}{${c.total}}`,
  `\\newcommand{\\cedarEquiv}{${c.equivalent_to_gate}}`,
  `\\newcommand{\\cedarTriangulated}{${c.agree_with_js_comparator}}`,
  `\\newcommand{\\cedarPredicates}{${c.config_surface.predicate_count}}`,
  `\\newcommand{\\cedarNaiveFalseAdmits}{${c.naive_default_false_admits}}`,
  `\\newcommand{\\cedarNaiveBrokenFamilies}{${c.naive_default_broken_families.length}}`,
  `\\newcommand{\\cedarAncestryFamilies}{${c.ancestry_load_bearing_families.length}}`,
  "",
].join("\n");

writeFileSync("results/latex/generated_policy_macros.tex", lines);
console.log("[policy-macros] wrote results/latex/generated_policy_macros.tex");
console.log(`  Cedar ${c.engine_version}: ${c.equivalent_to_gate}/${c.total} == gate; naive false-admits ${c.naive_default_false_admits} across ${c.naive_default_broken_families.length} families`);
