#!/usr/bin/env node
// Emit LaTeX macros for the OSS shared-store static-analysis result, read from the COMMITTED JSON
// (results/eval/oss-shared-store-analysis.json) so the paper numbers regenerate without re-cloning.
// Run: node scripts/export_oss_macros.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, "..");
const d = JSON.parse(readFileSync(join(REPO, "results", "eval", "oss-shared-store-analysis.json"), "utf8"));
const fw = d.frameworks;
const t = d.totals;
const pct = (x) => (Math.round(x * 10) / 10).toString();
const L = [
  "% Auto-generated by scripts/export_oss_macros.mjs from results/eval/oss-shared-store-analysis.json.",
  `\\newcommand{\\ossTotalSites}{${t.shared_store_read_sites}}`,
  `\\newcommand{\\ossUnbound}{${t.active_message_unbound}}`,
  `\\newcommand{\\ossPctUnbound}{${pct(t.pct_unbound)}}`,
  `\\newcommand{\\ossNframeworks}{${Object.keys(fw).length}}`,
];
const nm = { autogen: "Autogen", langgraph: "Langgraph", metagpt: "Metagpt" };
for (const [k, v] of Object.entries(fw)) {
  const C = nm[k] || (k[0].toUpperCase() + k.slice(1));
  L.push(`\\newcommand{\\oss${C}Sites}{${v.shared_store_read_sites}}`);
  L.push(`\\newcommand{\\oss${C}Unbound}{${v.active_message_unbound}}`);
  L.push(`\\newcommand{\\oss${C}Pct}{${pct(v.pct_unbound)}}`);
  L.push(`\\newcommand{\\oss${C}Sha}{${String(v.pinned_sha).slice(0, 10)}}`);
}
writeFileSync(join(REPO, "results", "latex", "generated_oss_macros.tex"), L.join("\n") + "\n");
process.stdout.write(`[oss:macros] wrote ${L.length - 1} macros (total ${t.active_message_unbound}/${t.shared_store_read_sites} = ${pct(t.pct_unbound)}%)\n`);
