// Emits results/latex/generated_redesign_macros.tex from the E13/E14/E15b analysis JSONs.
// No number is hand-typed into the paper for the redesign experiments.
import { readFileSync, writeFileSync, existsSync } from "node:fs";

// Filesystem reference-monitor PoC counts (scripts/poc_filesystem_mbm.mjs). Read if present; fall back to
// the committed counts so standalone macro generation never breaks. No number is hand-typed into the paper.
const fsPoc = existsSync("results/eval/poc-filesystem.json")
  ? JSON.parse(readFileSync("results/eval/poc-filesystem.json", "utf8"))
  : { hypotheses: 6, checks: 11, passed: 11 };
const fsGit = existsSync("results/eval/poc-filesystem-git.json")
  ? JSON.parse(readFileSync("results/eval/poc-filesystem-git.json", "utf8"))
  : { hypotheses: 4, checks: 11, passed: 11 };

// Conformance-suite sizes, machine-sourced so prose counts can't drift from the regenerated suites.
const secCov = existsSync("results/eval/secure-coverage-main.json")
  ? JSON.parse(readFileSync("results/eval/secure-coverage-main.json", "utf8")) : { cases: 180 };
const intCov = existsSync("results/eval/secure-coverage-integrity-flow.json")
  ? JSON.parse(readFileSync("results/eval/secure-coverage-integrity-flow.json", "utf8")) : { cases: 20 };

// Gate 2.0 kernel COST (scripts/bench_gate2_cost.mjs): per-operation wall-clock vs an ungated store read, and
// the linear scaling in closure size |C(m)|. Machine-indicative; the scientific claim is the LINEAR fit (R^2).
const cost = existsSync("results/eval/gate2-cost.json")
  ? JSON.parse(readFileSync("results/eval/gate2-cost.json", "utf8"))
  : { per_record_marginal_us: 0, fit_r2: 0, largest_n: 0, largest_query_ms: 0, largest_action_ms: 0, largest_query_overhead_x: 0, query_throughput_per_s: 0, action_throughput_per_s: 0 };

// Gate 2.0 SCALABILITY (scripts/bench_gate2_scale.mjs): latency linear in run size N (= ledger length),
// conflict-width scaling, storage/record, and crash-recovery (trusted-state restore). Machine-indicative.
const scale = existsSync("results/eval/gate2-scale.json")
  ? JSON.parse(readFileSync("results/eval/gate2-scale.json", "utf8"))
  : { query_per_record_us: 0, query_fit_r2: 0, largest_n: 0, largest_query_ms: 0, largest_action_ms: 0, storage_per_record_kb: 0, recovery_ms: 0 };

const e13 = JSON.parse(readFileSync("results/eval/e13-etc-analysis.json", "utf8"));
const e14 = JSON.parse(readFileSync("results/eval/e14-best-effort-analysis.json", "utf8"));
const prev = JSON.parse(readFileSync("results/eval/failure-prevalence-analysis.json", "utf8"));
const e16 = JSON.parse(readFileSync("results/eval/e16-locomo-analysis.json", "utf8"));
// E17 (live LangGraph) macros are WITHDRAWN (review M1): the numbers were an oracle-fallback
// artifact, so we do not emit \ma* macros and the figure shows a withdrawn note instead.
const e18 = JSON.parse(readFileSync("results/eval/e18-longrun-analysis.json", "utf8"));
const abl = JSON.parse(readFileSync("results/eval/ablation-family-split-analysis.json", "utf8"));
// Cross-model robustness (phase-6 dev24, C4 vs C5): a non-OpenAI model (Gemini) alongside the two
// OpenAI-family models, to show the gate effect is not OpenAI-family-specific (reviewer P2).
const xGem = JSON.parse(readFileSync("results/coupled-memory-phase6-live-dev24-gemini25flash-analysis.json", "utf8"));
const xNano = JSON.parse(readFileSync("results/coupled-memory-phase6-live-dev24-gpt5nano-analysis.json", "utf8"));
const xMini = JSON.parse(readFileSync("results/coupled-memory-phase6-live-dev24-gpt5mini-analysis.json", "utf8"));
// Cross-model robustness on the MAIN split (headline): Gemini second family vs the gpt-family aggregate.
const xGemMain = JSON.parse(readFileSync("results/coupled-memory-phase6-live-main40-gemini25flash-analysis.json", "utf8"));

const pct = (x) => `${(x * 100).toFixed(1)}\\%`;
const f3 = (x) => x.toFixed(3);
const f2 = (x) => x.toFixed(2);

const c = e13.combined;
const b1 = e14.baselines.B1, b2 = e14.baselines.B2;

const lines = [
  "% Auto-generated by scripts/export_redesign_macros.mjs -- redesign (E13/E14/E15b) numbers.",
  // E13 blind ETC
  `\\newcommand{\\etcDelta}{${f3(c.etc.delta)}}`,
  `\\newcommand{\\etcCIlow}{${f3(c.etc.ci95[0])}}`,
  `\\newcommand{\\etcCIhigh}{${f3(c.etc.ci95[1])}}`,
  `\\newcommand{\\etcCFour}{${pct(c.etc.c4)}}`,
  `\\newcommand{\\etcCFive}{${pct(c.etc.c5)}}`,
  `\\newcommand{\\etcFfcrDelta}{${f3(c.ffcr_for_reference.delta)}}`,
  `\\newcommand{\\etcNpairs}{${c.n_pairs}}`,
  `\\newcommand{\\etcEoneDelta}{${f3(e13.e1.etc.delta)}}`,
  `\\newcommand{\\etcEthreeDelta}{${f3(e13.e3.etc.delta)}}`,
  // E14 best-effort baselines
  `\\newcommand{\\beContentOnly}{${pct(b1.ffcr)}}`,
  `\\newcommand{\\beMetaAware}{${pct(b2.ffcr)}}`,
  `\\newcommand{\\beMetaDelta}{${f3(b2.delta_vs_gate)}}`,
  `\\newcommand{\\beMetaCIlow}{${f3(b2.ci95[0])}}`,
  `\\newcommand{\\beMetaCIhigh}{${f3(b2.ci95[1])}}`,
  // E15b prevalence
  `\\newcommand{\\prevSeNative}{${pct(prev.se_native_E3.c4_failure_rate)}}`,
  `\\newcommand{\\prevConstructed}{${pct(prev.constructed_E1.c4_failure_rate)}}`,
  // E16 external (LoCoMo) -- honest scoping (null/negative) result
  `\\newcommand{\\eSixDelta}{${f3(e16.overall.delta)}}`,
  `\\newcommand{\\eSixCIlow}{${f3(e16.overall.ci95[0])}}`,
  `\\newcommand{\\eSixCIhigh}{${f3(e16.overall.ci95[1])}}`,
  `\\newcommand{\\eSixN}{${e16.overall.n}}`,
  // E17 live multi-agent LangGraph: WITHDRAWN (oracle-fallback artifact); no \ma* macros emitted.
  // E18 long-running multi-agent workflow benchmark (multi-turn, end-to-end)
  `\\newcommand{\\lrCFour}{${pct(e18.c4_success)}}`,
  `\\newcommand{\\lrCFive}{${pct(e18.c5_success)}}`,
  `\\newcommand{\\lrDelta}{${f3(e18.delta)}}`,
  `\\newcommand{\\lrCIlow}{${f3(e18.ci95[0])}}`,
  `\\newcommand{\\lrCIhigh}{${f3(e18.ci95[1])}}`,
  `\\newcommand{\\lrN}{${e18.n_episodes}}`,
  `\\newcommand{\\lrUniqueEpisodes}{${e18.unique_episodes ?? e18.n_episodes}}`,
  `\\newcommand{\\lrFamilies}{${e18.families ?? "?"}}`,
  `\\newcommand{\\lrModels}{${e18.models ?? "?"}}`,
  `\\newcommand{\\lrUnits}{${e18.model_episode_units ?? e18.n_episodes}}`,
  `\\newcommand{\\lrContamCFour}{${pct(e18.c4_contamination_rate)}}`,
  // E9 single-check ablation split (Fig. 4D) -- gate-level double dissociation
  `\\newcommand{\\ablPolStatusFamilies}{${abl.groups.policy_status_cued.n_families}}`,
  `\\newcommand{\\ablProvFamilies}{${abl.groups.provenance_cued.n_families}}`,
  `\\newcommand{\\ablOtherFamilies}{${abl.groups.other_bound.n_families}}`,
  `\\newcommand{\\ablPolStatusUnderNoPolicy}{${pct(abl.groups.policy_status_cued.gate_protection.no_policy)}}`,
  `\\newcommand{\\ablPolStatusUnderNoProv}{${pct(abl.groups.policy_status_cued.gate_protection.no_provenance)}}`,
  `\\newcommand{\\ablProvUnderNoProv}{${pct(abl.groups.provenance_cued.gate_protection.no_provenance)}}`,
  `\\newcommand{\\ablProvUnderNoPolicy}{${pct(abl.groups.provenance_cued.gate_protection.no_policy)}}`,
  `\\newcommand{\\ablOtherUnderBoth}{${pct(abl.groups.other_bound.gate_protection.no_policy)}}`,
  // Cross-model robustness (phase-6 dev24, C4 vs C5). Gemini is the non-OpenAI model.
  `\\newcommand{\\xModelNpairs}{${xGem.paired_n}}`,
  `\\newcommand{\\xGeminiModel}{${xGem.model}}`,
  `\\newcommand{\\xGeminiForbCFour}{${xGem.c4_forbidden_memory}}`,
  `\\newcommand{\\xGeminiForbCFive}{${xGem.c5_forbidden_memory}}`,
  `\\newcommand{\\xGeminiForbRed}{${f3(xGem.paired_forbidden_memory_delta)}}`,
  `\\newcommand{\\xGeminiForbRedCIlow}{${f3(xGem.paired_forbidden_memory_delta_ci95[0])}}`,
  `\\newcommand{\\xGeminiForbRedCIhigh}{${f3(xGem.paired_forbidden_memory_delta_ci95[1])}}`,
  `\\newcommand{\\xGeminiSuccCFour}{${pct(xGem.c4_successes / xGem.c4_cases)}}`,
  `\\newcommand{\\xGeminiSuccCFive}{${pct(xGem.c5_successes / xGem.c5_cases)}}`,
  `\\newcommand{\\xGeminiSuccDelta}{${f3(xGem.paired_success_delta)}}`,
  `\\newcommand{\\xGeminiSuccDeltaCIlow}{${f3(xGem.paired_success_delta_ci95[0])}}`,
  `\\newcommand{\\xGeminiSuccDeltaCIhigh}{${f3(xGem.paired_success_delta_ci95[1])}}`,
  // Gemini on the MAIN (headline) split, n=xGemMainNpairs: the C4->C5 selection improvement and
  // forbidden-memory elimination replicate on a second family at ~the gpt-family magnitude.
  `\\newcommand{\\xGemMainNpairs}{${xGemMain.paired_n}}`,
  `\\newcommand{\\xGemMainSuccCFour}{${pct(xGemMain.c4_successes / xGemMain.c4_cases)}}`,
  `\\newcommand{\\xGemMainSuccCFive}{${pct(xGemMain.c5_successes / xGemMain.c5_cases)}}`,
  `\\newcommand{\\xGemMainSuccDelta}{${f3(xGemMain.paired_success_delta)}}`,
  `\\newcommand{\\xGemMainSuccDeltaCIlow}{${f3(xGemMain.paired_success_delta_ci95[0])}}`,
  `\\newcommand{\\xGemMainSuccDeltaCIhigh}{${f3(xGemMain.paired_success_delta_ci95[1])}}`,
  `\\newcommand{\\xGemMainForbCFour}{${xGemMain.c4_forbidden_memory}}`,
  `\\newcommand{\\xGemMainForbCFive}{${xGemMain.c5_forbidden_memory}}`,
  `\\newcommand{\\xNanoForbCFour}{${xNano.c4_forbidden_memory}}`,
  `\\newcommand{\\xNanoForbCFive}{${xNano.c5_forbidden_memory}}`,
  `\\newcommand{\\xNanoSuccCFive}{${pct(xNano.c5_successes / xNano.c5_cases)}}`,
  `\\newcommand{\\xMiniForbCFour}{${xMini.c4_forbidden_memory}}`,
  `\\newcommand{\\xMiniForbCFive}{${xMini.c5_forbidden_memory}}`,
  `\\newcommand{\\xMiniSuccCFive}{${pct(xMini.c5_successes / xMini.c5_cases)}}`,
  // Filesystem reference-monitor PoC (real-directory hypotheses H1--H6).
  `\\newcommand{\\fsHypotheses}{${fsPoc.hypotheses}}`,
  `\\newcommand{\\fsChecks}{${fsPoc.checks}}`,
  `\\newcommand{\\fsPassed}{${fsPoc.passed}}`,
  // Conformance-suite sizes (digit form), machine-sourced.
  `\\newcommand{\\secureSuiteN}{${secCov.cases}}`,
  `\\newcommand{\\integritySetN}{${intCov.cases}}`,
  // Real-git filesystem PoC.
  `\\newcommand{\\fsGitChecks}{${fsGit.checks}}`,
  `\\newcommand{\\fsGitPassed}{${fsGit.passed}}`,
  // Gate 2.0 kernel cost (machine-indicative; headline is the linear-in-|C(m)| fit).
  `\\newcommand{\\costPerRecordMs}{${(cost.per_record_marginal_us / 1000).toFixed(1)}}`,
  `\\newcommand{\\costFitRsq}{${cost.fit_r2.toFixed(2)}}`,
  `\\newcommand{\\costLargestN}{${cost.largest_n}}`,
  `\\newcommand{\\costQueryMs}{${Math.round(cost.largest_query_ms)}}`,
  `\\newcommand{\\costActionMs}{${Math.round(cost.largest_action_ms)}}`,
  `\\newcommand{\\costOverhead}{${Math.round(cost.largest_query_overhead_x)}}`,
  `\\newcommand{\\costQueryThroughput}{${Math.round(cost.query_throughput_per_s)}}`,
  // Gate 2.0 scalability (machine-indicative; headline is the linear-in-N fit).
  `\\newcommand{\\scalePerRecordMs}{${(scale.query_per_record_us / 1000).toFixed(1)}}`,
  `\\newcommand{\\scaleFitRsq}{${scale.query_fit_r2.toFixed(2)}}`,
  `\\newcommand{\\scaleLargestN}{${scale.largest_n}}`,
  `\\newcommand{\\scaleLargestQuerySec}{${(scale.largest_query_ms / 1000).toFixed(1)}}`,
  `\\newcommand{\\scaleLargestActionSec}{${(scale.largest_action_ms / 1000).toFixed(1)}}`,
  `\\newcommand{\\scaleStoragePerRecordKb}{${scale.storage_per_record_kb.toFixed(2)}}`,
  `\\newcommand{\\scaleRecoveryMs}{${Math.round(scale.recovery_ms)}}`,
  "",
].join("\n");

writeFileSync("results/latex/generated_redesign_macros.tex", lines);
console.log("[redesign-macros] wrote results/latex/generated_redesign_macros.tex");
console.log(`  ETC delta ${f3(c.etc.delta)} [${f3(c.etc.ci95[0])},${f3(c.etc.ci95[1])}] vs FFCR ${f3(c.ffcr_for_reference.delta)}`);
console.log(`  B1 ${pct(b1.ffcr)}  B2 ${pct(b2.ffcr)} (gate 100%, +${f3(b2.delta_vs_gate)})`);
console.log(`  prevalence SE-native ${pct(prev.se_native_E3.c4_failure_rate)}, constructed ${pct(prev.constructed_E1.c4_failure_rate)}`);
